"use client";

/**
 * Hero.tsx — BSL Construction
 * -------------------------------------------------------------------------
 * Scroll-scrubbed hero, rebuilt around a canvas + pre-extracted frame
 * sequence instead of <video> + currentTime seeking.
 *
 * WHY THE REWRITE
 * ----------------------------------------------------------------------
 * The previous version drove scrub by setting video.currentTime on every
 * rAF tick. That works, but every seek forces the browser's video decoder
 * to hunt for the nearest keyframe and decode forward to the target frame
 * — real, unavoidable async work, most expensive exactly where it hurts
 * most (mobile Chrome/Safari). No amount of threshold tuning, smoothing,
 * or seek-gating removes that cost; it can only redistribute it, which is
 * why the old version could still stutter on a fast flick-scroll.
 *
 * This version instead:
 *   1. Extracts the clip to a numbered sequence of still images at build
 *      time (ffmpeg command below).
 *   2. Loads those images with the browser's normal image pipeline.
 *   3. On scroll, picks the frame whose index matches progress and draws
 *      it onto a <canvas> with drawImage().
 *
 * A frame "seek" is now just an array index + a synchronous canvas draw —
 * no decode, no async seek, nothing to stall. This is the same technique
 * behind most award-winning scroll-hero sites (Apple product pages,
 * Stripe, etc). It also removes the iOS/Android autoplay "priming" hack
 * entirely, since there's no <video> element to fight with.
 *
 * BUILD STEP — generate the frames before shipping
 * ----------------------------------------------------------------------
 *   # duration of your source clip, in seconds
 *   DURATION=$(ffprobe -v error -show_entries format=duration -of csv=p=0 video1.mp4)
 *
 *   # Desktop set — 96 frames, 1920px wide, JPEG
 *   mkdir -p public/hero-frames/desktop
 *   ffmpeg -i video1.mp4 -vf "fps=$(echo "96/$DURATION" | bc -l),scale=1920:-2" \
 *     -q:v 4 public/hero-frames/desktop/frame-%04d.jpg
 *
 *   # Mobile set — fewer frames, smaller width, saves mobile data
 *   mkdir -p public/hero-frames/mobile
 *   ffmpeg -i video1.mp4 -vf "fps=$(echo "60/$DURATION" | bc -l),scale=900:-2" \
 *     -q:v 5 public/hero-frames/mobile/frame-%04d.jpg
 *
 * (Using JPEG here because it's always available in every ffmpeg build —
 * some ffmpeg installs, notably some Homebrew setups, don't ship with the
 * WebP encoder compiled in.)
 *
 * Tune the frame counts to your clip length / motion: more frames =
 * smoother but bigger download. 60-100 frames is a good starting point
 * for a 4-10s clip; each JPEG typically lands ~20-45KB at these settings,
 * so a 96-frame desktop set is usually ~2.5-4MB total — loaded in the
 * background, not blocking first paint (see PRIORITY_FRAMES below).
 *
 * IF YOU CAN'T PRE-EXTRACT FRAMES
 * ----------------------------------------------------------------------
 * If frame extraction isn't feasible in your pipeline, the video-seeking
 * approach can still be improved somewhat: raise SEEK_THRESHOLD to
 * roughly 1/(2*targetFPS) so you're never seeking finer than a frame
 * boundary, gate new seeks behind the video's `requestVideoFrameCallback`
 * instead of firing on every rAF tick, and fully pre-buffer the source as
 * a blob (fetch + URL.createObjectURL) so seeks resolve against local
 * data rather than a network stream. That will reduce jank but won't
 * eliminate it the way frame-sequence scrubbing does.
 * -------------------------------------------------------------------------
 */

import { useEffect, useRef, useState } from "react";

const POSTER_SRC = "/hero-poster.jpg"; // shown until first frame batch is ready

// Frame sets — one per breakpoint, generated by the ffmpeg commands above.
const MOBILE_BREAKPOINT = 768;
const FRAME_SETS = {
  desktop: {
    count: 96,
    path: (i: number) => `/hero-frames/desktop/frame-${String(i + 1).padStart(4, "0")}.jpg`,
  },
  mobile: {
    count: 60,
    path: (i: number) => `/hero-frames/mobile/frame-${String(i + 1).padStart(4, "0")}.jpg`,
  },
} as const;

// How many frames to block on before revealing the canvas. Keeps first
// paint fast; the rest load in the background with limited concurrency.
const PRIORITY_FRAMES = 14;
const BACKGROUND_LOAD_CONCURRENCY = 4;

// Exponential smoothing factor for scroll -> frame-progress follow. Safe
// to run tighter than the old video version (0.2-0.45) because there's no
// seek latency to "catch up" from — frame draws are effectively instant.
const SMOOTHING = 0.6;
const MAX_DT = 1 / 24;
const OBSERVER_MARGIN = "200px 0px 200px 0px";
// Cap device pixel ratio for the canvas backing store — 3x on a phone is
// wasted fill-rate for a full-bleed hero image.
const MAX_DPR = 2;

const SEO_PHRASES = ["New Builds", "Renovations", "Home Maintenance", "General Contracting"];

const STAGES: { at: number; text: string }[] = [
  { at: 0.0, text: "Timber-frame construction, built to last." },
  { at: 0.45, text: "Full renovations and home extensions, done right." },
  { at: 0.8, text: "Ongoing home maintenance — the job doesn't end at handover." },
];

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}

function getStageText(progress: number) {
  let current = STAGES[0].text;
  for (const item of STAGES) {
    if (progress >= item.at) current = item.text;
  }
  return current;
}

function frameFactor(smoothing: number, dt: number) {
  return 1 - Math.pow(1 - smoothing, dt * 60);
}

function loadImage(src: string) {
  return new Promise<HTMLImageElement>((resolve, reject) => {
    const img = new Image();
    img.decoding = "async";
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

// The Network Information API isn't in TypeScript's built-in DOM types
// (it's still non-standard / Chromium-only), so it's typed manually here
// instead of reaching for `any`. Every field is optional since support
// is inconsistent across browsers.
interface NetworkInformation {
  saveData?: boolean;
  effectiveType?: "slow-2g" | "2g" | "3g" | "4g";
}
interface NavigatorWithConnection extends Navigator {
  connection?: NetworkInformation;
}

export default function Hero() {
  const scrollSpaceRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const progressFillRef = useRef<HTMLDivElement>(null);
  const textLayerARef = useRef<HTMLHeadingElement>(null);
  const textLayerBRef = useRef<HTMLHeadingElement>(null);
  const activeLayerRef = useRef(0);
  const rafIdRef = useRef<number | null>(null);
  const inViewRef = useRef(true);
  const lastTextRef = useRef(STAGES[0].text);
  const lastFrameTimeRef = useRef<number | null>(null);
  const displayedProgressRef = useRef(0);
  const geometryRef = useRef({ top: 0, total: 0 });
  const framesRef = useRef<(HTMLImageElement | null)[]>([]);
  const desiredFrameIndexRef = useRef(0);
  const paintedFrameIndexRef = useRef(-1);
  const canvasSizeRef = useRef({ w: 0, h: 0 });
  const useFallbackRef = useRef(false);

  const [isReady, setIsReady] = useState(false);
  const [useFallback, setUseFallback] = useState(false);

  useEffect(() => {
    useFallbackRef.current = useFallback;
  }, [useFallback]);

  // Runs once on mount — readiness/fallback are tracked via refs/closures
  // rather than effect deps so the rAF loop and IntersectionObserver never
  // get torn down and rebuilt mid-scroll.
  useEffect(() => {
    const canvas = canvasRef.current;
    const scrollSpace = scrollSpaceRef.current;
    if (!canvas || !scrollSpace) return;

    const ctx = canvas.getContext("2d", { alpha: false });
    if (!ctx) {
      setUseFallback(true);
      return;
    }

    const reduceMotionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");

    const variant: keyof typeof FRAME_SETS =
      window.innerWidth <= MOBILE_BREAKPOINT ? "mobile" : "desktop";
    const { count: FRAME_COUNT, path: framePath } = FRAME_SETS[variant];
    framesRef.current = new Array(FRAME_COUNT).fill(null);

    const measureGeometry = () => {
      const rect = scrollSpace.getBoundingClientRect();
      const top = rect.top + window.scrollY;
      const total = scrollSpace.offsetHeight - window.innerHeight;
      geometryRef.current = { top, total: Math.max(total, 0) };
    };

    const getNearestFrame = (index: number) => {
      const frames = framesRef.current;
      if (frames[index]) return frames[index];
      for (let d = 1; d < frames.length; d++) {
        if (frames[index - d]) return frames[index - d];
        if (frames[index + d]) return frames[index + d];
      }
      return null;
    };

    const drawFrame = (index: number, force = false) => {
      if (!force && index === paintedFrameIndexRef.current) return;
      const img = getNearestFrame(index);
      const { w, h } = canvasSizeRef.current;
      if (!img || w === 0 || h === 0) return;

      const canvasRatio = w / h;
      const imgRatio = img.naturalWidth / img.naturalHeight;
      let sx: number, sy: number, sw: number, sh: number;
      if (imgRatio > canvasRatio) {
        sh = img.naturalHeight;
        sw = sh * canvasRatio;
        sx = (img.naturalWidth - sw) / 2;
        sy = 0;
      } else {
        sw = img.naturalWidth;
        sh = sw / canvasRatio;
        sx = 0;
        sy = (img.naturalHeight - sh) / 2;
      }
      ctx.drawImage(img, sx, sy, sw, sh, 0, 0, w, h);
      paintedFrameIndexRef.current = index;
    };

    const resizeCanvas = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR);
      const rect = canvas.getBoundingClientRect();
      const w = Math.round(rect.width * dpr);
      const h = Math.round(rect.height * dpr);
      if (canvas.width !== w || canvas.height !== h) {
        canvas.width = w;
        canvas.height = h;
      }
      canvasSizeRef.current = { w, h };
      // Canvas size changed, so the previous paint no longer matches —
      // force a redraw at the desired frame even if the index is unchanged.
      drawFrame(desiredFrameIndexRef.current, true);
    };

    let cancelled = false;

    const loadFrames = async () => {
      const conn = (navigator as NavigatorWithConnection).connection;
      const dataSaver = Boolean(conn?.saveData);
      const slowConn = conn?.effectiveType && ["slow-2g", "2g"].includes(conn.effectiveType);
      if (dataSaver || slowConn) {
        // Skip the frame sequence entirely — poster image stays as the
        // hero. Scroll-linked text/progress bar still work (cheap, no
        // network cost), only the frame scrub is disabled.
        setUseFallback(true);
        return;
      }

      try {
        const priorityCount = Math.min(PRIORITY_FRAMES, FRAME_COUNT);
        const priorityIdx = Array.from({ length: priorityCount }, (_, i) => i);
        const priorityImgs = await Promise.all(priorityIdx.map((i) => loadImage(framePath(i))));
        if (cancelled) return;
        priorityIdx.forEach((i, idx) => {
          framesRef.current[i] = priorityImgs[idx];
        });

        drawFrame(desiredFrameIndexRef.current, true);
        setIsReady(true);

        const rest = Array.from({ length: FRAME_COUNT }, (_, i) => i).filter(
          (i) => !framesRef.current[i]
        );
        let cursor = 0;
        const workers = Array.from({ length: BACKGROUND_LOAD_CONCURRENCY }, async () => {
          while (cursor < rest.length) {
            const i = rest[cursor++];
            try {
              const img = await loadImage(framePath(i));
              if (cancelled) return;
              framesRef.current[i] = img;
            } catch {
              // Leave as null — getNearestFrame() falls back to the
              // closest loaded neighbor, so a missed frame never shows
              // as blank.
            }
          }
        });
        await Promise.all(workers);
      } catch {
        if (!cancelled) setUseFallback(true);
      }
    };

    measureGeometry();
    resizeCanvas();
    loadFrames();

    const textLayers = [textLayerARef, textLayerBRef];

    const swapText = (nextText: string) => {
      const activeIndex = activeLayerRef.current;
      const nextIndex = (activeIndex + 1) % 2;
      const activeEl = textLayers[activeIndex].current;
      const nextEl = textLayers[nextIndex].current;
      if (!activeEl || !nextEl) return;

      if (nextEl.dataset.text !== nextText) {
        nextEl.textContent = nextText;
        nextEl.dataset.text = nextText;
      }

      nextEl.classList.remove("hero-text-hide");
      nextEl.classList.add("hero-text-show");
      activeEl.classList.remove("hero-text-show");
      activeEl.classList.add("hero-text-hide");

      activeLayerRef.current = nextIndex;
    };

    const loop = (now: number) => {
      if (!inViewRef.current) {
        rafIdRef.current = null;
        lastFrameTimeRef.current = null;
        return;
      }

      const last = lastFrameTimeRef.current ?? now;
      const dt = clamp((now - last) / 1000, 0, MAX_DT);
      lastFrameTimeRef.current = now;

      const { top, total } = geometryRef.current;
      const scrolled = clamp(window.scrollY - top, 0, total);
      const progress = total > 0 ? scrolled / total : 0;

      const factor = reduceMotionQuery.matches ? 1 : frameFactor(SMOOTHING, dt);
      displayedProgressRef.current += (progress - displayedProgressRef.current) * factor;

      const frameIndex = Math.round(
        clamp(displayedProgressRef.current, 0, 1) * (FRAME_COUNT - 1)
      );
      desiredFrameIndexRef.current = frameIndex;
      if (!useFallbackRef.current) drawFrame(frameIndex);

      const nextText = getStageText(progress);
      if (nextText !== lastTextRef.current) {
        lastTextRef.current = nextText;
        swapText(nextText);
      }

      if (progressFillRef.current) {
        progressFillRef.current.style.setProperty("--hero-progress", `${progress * 100}%`);
      }

      rafIdRef.current = requestAnimationFrame(loop);
    };

    rafIdRef.current = requestAnimationFrame(loop);

    const observer = new IntersectionObserver(
      ([entry]) => {
        inViewRef.current = entry.isIntersecting;
        if (entry.isIntersecting && rafIdRef.current === null) {
          lastFrameTimeRef.current = null;
          rafIdRef.current = requestAnimationFrame(loop);
        }
      },
      { rootMargin: OBSERVER_MARGIN }
    );
    observer.observe(scrollSpace);

    let resizeRaf: number | null = null;
    const handleResize = () => {
      if (resizeRaf !== null) return;
      resizeRaf = requestAnimationFrame(() => {
        measureGeometry();
        resizeCanvas();
        resizeRaf = null;
      });
    };
    window.addEventListener("resize", handleResize, { passive: true });
    window.addEventListener("orientationchange", handleResize, { passive: true });

    return () => {
      cancelled = true;
      window.removeEventListener("resize", handleResize);
      window.removeEventListener("orientationchange", handleResize);
      if (resizeRaf !== null) cancelAnimationFrame(resizeRaf);
      if (rafIdRef.current !== null) cancelAnimationFrame(rafIdRef.current);
      observer.disconnect();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div ref={scrollSpaceRef} data-hero-root className="hero-scroll-space">
      <div className="hero-sticky">
        <img src={POSTER_SRC} alt="" aria-hidden="true" className="hero-poster" />
        <canvas
          ref={canvasRef}
          aria-hidden="true"
          className={`hero-canvas ${isReady && !useFallback ? "hero-canvas-ready" : ""}`}
        />

        <div className="hero-overlay" />

        <div className="hero-progress">
          <div ref={progressFillRef} className="hero-progress-fill" />
        </div>

        <div className="hero-caption-stack">
          <div className="hero-caption-glow" aria-hidden="true" />
          <h1
            ref={textLayerARef}
            className="hero-heading hero-text-show"
            data-text={STAGES[0].text}
          >
            {STAGES[0].text}
          </h1>
          <h1
            ref={textLayerBRef}
            className="hero-heading hero-text-hide"
            data-text=""
          />
        </div>

        <div className="hero-scroll-hint" aria-hidden="true">
          <span className="hero-scroll-line" />
        </div>

        <div className="hero-seo">
          <div className="hero-seo-track">
            {SEO_PHRASES.map((phrase, i) => (
              <span key={phrase} className="hero-seo-pill">
                {phrase}
                {i < SEO_PHRASES.length - 1 && (
                  <span className="hero-seo-dot">•</span>
                )}
              </span>
            ))}
          </div>
        </div>
      </div>

      <style jsx>{`
        .hero-scroll-space {
          /* Scroll runway length — how much scroll distance it takes to
             scrub through the whole clip. Overridden per breakpoint below
             so the pacing feels right on phones vs. desktop, instead of
             using one fixed length for every viewport. */
          --hero-scroll-length: 170vh;
          height: var(--hero-scroll-length);
          position: relative;
        }

        .hero-sticky {
          position: sticky;
          top: 0;
          height: 100vh;
          height: 100dvh;
          overflow: hidden;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .hero-poster,
        .hero-canvas {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          z-index: 0;
        }

        .hero-poster {
          object-fit: cover;
        }

        .hero-canvas {
          display: block;
          opacity: 0;
          transition: opacity 0.5s ease;
          will-change: opacity;
          transform: translateZ(0);
        }
        .hero-canvas-ready {
          opacity: 1;
        }

        .hero-overlay {
          position: absolute;
          inset: 0;
          background: linear-gradient(
            0deg,
            rgba(0, 0, 0, 0.72) 0%,
            rgba(0, 0, 0, 0.32) 30%,
            rgba(0, 0, 0, 0.12) 48%,
            rgba(0, 0, 0, 0.16) 100%
          );
          z-index: 1;
        }

        /* ----------------------------------------------------------------
           Progress bar — vertical rail on desktop by default. Driven by
           the --hero-progress custom property set from rAF.
           ---------------------------------------------------------------- */
        .hero-progress {
          position: absolute;
          right: 0.75rem;
          top: 7.5rem;
          width: 4px;
          height: calc(100% - 12rem);
          max-height: 220px;
          background: rgba(255, 255, 255, 0.18);
          border-radius: 2px;
          z-index: 3;
        }
        .hero-progress-fill {
          position: absolute;
          bottom: 0;
          left: 0;
          width: 100%;
          height: var(--hero-progress, 0%);
          background: #e0a077;
          border-radius: 2px;
          transition: height 0.05s linear;
        }

        .hero-caption-stack {
          position: absolute;
          bottom: 21%;
          left: 0;
          right: 0;
          z-index: 2;
          width: min(92vw, 560px);
          margin: 0 auto;
          box-sizing: border-box;
          padding: 0 1rem;
          min-height: 5rem;
        }

        .hero-caption-glow {
          position: absolute;
          inset: -1.5rem -1rem;
          background: radial-gradient(
            ellipse at center,
            rgba(0, 0, 0, 0.38) 0%,
            rgba(0, 0, 0, 0.16) 55%,
            transparent 80%
          );
          z-index: -1;
          pointer-events: none;
        }

        .hero-heading {
          position: absolute;
          inset: 0;
          margin: 0;
          font-size: clamp(1.75rem, 6vw, 2.75rem);
          font-weight: 700;
          line-height: 1.25;
          color: #fff;
          text-align: center;
          text-shadow: 0 2px 18px rgba(0, 0, 0, 0.55);
          transition: opacity 0.4s ease, transform 0.4s ease;
          will-change: opacity, transform;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .hero-text-show {
          opacity: 1;
          transform: translateY(0);
        }
        .hero-text-hide {
          opacity: 0;
          transform: translateY(14px);
        }

        .hero-scroll-hint {
          position: absolute;
          bottom: 5.5rem;
          left: 50%;
          transform: translateX(-50%);
          z-index: 2;
          width: 22px;
          height: 34px;
          border: 2px solid rgba(255, 255, 255, 0.55);
          border-radius: 12px;
          display: flex;
          justify-content: center;
          pointer-events: none;
        }
        .hero-scroll-line {
          display: block;
          width: 3px;
          height: 7px;
          margin-top: 7px;
          background: rgba(255, 255, 255, 0.9);
          border-radius: 2px;
          animation: hero-bounce 1.6s ease-in-out infinite;
        }

        @keyframes hero-bounce {
          0%,
          100% {
            transform: translateY(0);
            opacity: 1;
          }
          50% {
            transform: translateY(8px);
            opacity: 0.5;
          }
        }

        /* ----------------------------------------------------------------
           SEO strip — wraps/centers on desktop by default; overridden to a
           horizontally scrollable snap row on mobile below.
           ---------------------------------------------------------------- */
        .hero-seo {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          z-index: 2;
          background: rgba(11, 11, 13, 0.45);
          backdrop-filter: blur(6px);
          -webkit-backdrop-filter: blur(6px);
        }
        .hero-seo-track {
          padding: 0.85rem 1rem;
          padding-bottom: calc(0.85rem + env(safe-area-inset-bottom));
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
          gap: 0.35rem 1rem;
        }
        .hero-seo-pill {
          font-size: clamp(0.65rem, 1.4vw, 0.75rem);
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color: rgba(255, 255, 255, 0.78);
          font-weight: 600;
          white-space: nowrap;
        }
        .hero-seo-dot {
          margin-inline-start: 1rem;
          color: rgba(255, 255, 255, 0.28);
        }

        /* ----------------------------------------------------------------
           Very small phones
           ---------------------------------------------------------------- */
        @media (max-width: 380px) {
          .hero-scroll-space {
            --hero-scroll-length: 125vh;
          }
          .hero-caption-stack {
            padding: 0 0.5rem;
            bottom: 23%;
            min-height: 6.5rem;
          }
          .hero-heading {
            font-size: clamp(1.45rem, 7.5vw, 1.85rem);
            line-height: 1.22;
          }
        }

        /* ----------------------------------------------------------------
           Phones / small screens — full-bleed 100dvh sticky viewport,
           top-loading progress bar, horizontally scrollable SEO strip.
           ---------------------------------------------------------------- */
        @media (max-width: 768px) {
          .hero-scroll-space {
            --hero-scroll-length: 130vh;
          }
          .hero-sticky {
            height: 100dvh;
          }

          .hero-overlay {
            background: linear-gradient(
              0deg,
              rgba(0, 0, 0, 0.78) 0%,
              rgba(0, 0, 0, 0.4) 26%,
              rgba(0, 0, 0, 0.14) 46%,
              rgba(0, 0, 0, 0.18) 100%
            );
          }

          /* Progress becomes a slim top-loading bar, safe-area aware. */
          .hero-progress {
            top: env(safe-area-inset-top, 0px);
            left: 0;
            right: 0;
            width: 100%;
            height: 3px;
            max-height: none;
            border-radius: 0;
            background: rgba(255, 255, 255, 0.16);
          }
          .hero-progress-fill {
            top: 0;
            bottom: auto;
            height: 100%;
            width: var(--hero-progress, 0%);
            border-radius: 0;
            transition: width 0.05s linear;
          }

          .hero-caption-stack {
            bottom: calc(6.75rem + env(safe-area-inset-bottom));
            width: min(90vw, 480px);
            min-height: 6rem;
          }
          .hero-heading {
            font-size: clamp(1.6rem, 6.6vw, 2.1rem);
            line-height: 1.24;
            letter-spacing: -0.01em;
          }

          .hero-scroll-hint {
            bottom: calc(4.5rem + env(safe-area-inset-bottom));
            width: 18px;
            height: 28px;
          }
          .hero-scroll-line {
            height: 6px;
            margin-top: 6px;
          }

          /* SEO strip: single row, horizontally scrollable, edge-faded. */
          .hero-seo-track {
            flex-wrap: nowrap;
            justify-content: flex-start;
            overflow-x: auto;
            overflow-y: hidden;
            scroll-snap-type: x proximity;
            -webkit-overflow-scrolling: touch;
            scrollbar-width: none;
            padding: 0.7rem 1.25rem;
            padding-bottom: calc(0.7rem + env(safe-area-inset-bottom));
            gap: 0.35rem 0.85rem;
            mask-image: linear-gradient(
              to right,
              transparent 0,
              black 20px,
              black calc(100% - 20px),
              transparent 100%
            );
            -webkit-mask-image: linear-gradient(
              to right,
              transparent 0,
              black 20px,
              black calc(100% - 20px),
              transparent 100%
            );
          }
          .hero-seo-track::-webkit-scrollbar {
            display: none;
          }
          .hero-seo-pill {
            scroll-snap-align: center;
            font-size: 0.7rem;
          }
          .hero-seo-dot {
            margin-inline-start: 0.85rem;
          }
        }

        /* ----------------------------------------------------------------
           Short-landscape phones — dvh is tiny here, so trim vertical
           chrome aggressively and drop the scroll hint entirely.
           ---------------------------------------------------------------- */
        @media (max-width: 900px) and (max-height: 500px) and (orientation: landscape) {
          .hero-scroll-space {
            --hero-scroll-length: 220vh;
          }
          .hero-caption-stack {
            bottom: 5rem;
            width: min(80vw, 460px);
            min-height: 3.5rem;
          }
          .hero-heading {
            font-size: clamp(1.15rem, 4.5vw, 1.5rem);
            line-height: 1.2;
          }
          .hero-scroll-hint {
            display: none;
          }
          .hero-seo-track {
            padding-top: 0.5rem;
            padding-bottom: calc(0.5rem + env(safe-area-inset-bottom));
          }
        }

        /* ----------------------------------------------------------------
           Tablets
           ---------------------------------------------------------------- */
        @media (min-width: 769px) and (max-width: 1024px) {
          .hero-scroll-space {
            --hero-scroll-length: 155vh;
          }
          .hero-caption-stack {
            width: min(70vw, 600px);
          }
        }

        /* ----------------------------------------------------------------
           Desktop refinements
           ---------------------------------------------------------------- */
        @media (min-width: 769px) {
          .hero-caption-stack {
            bottom: 16%;
            width: min(78vw, 640px);
            padding: 0;
          }
          .hero-heading {
            font-size: clamp(2rem, 3.6vw, 2.75rem);
          }
          .hero-scroll-hint {
            display: none;
          }
        }

        /* ----------------------------------------------------------------
           Large / ultra-wide desktop
           ---------------------------------------------------------------- */
        @media (min-width: 1440px) {
          .hero-scroll-space {
            --hero-scroll-length: 190vh;
          }
          .hero-caption-stack {
            width: min(56vw, 720px);
          }
          .hero-heading {
            font-size: clamp(2.25rem, 3vw, 3.25rem);
          }
        }

        @media (max-height: 560px) and (min-width: 769px) {
          .hero-caption-stack {
            bottom: 20%;
          }
          .hero-scroll-hint {
            display: none;
          }
        }

        /* ----------------------------------------------------------------
           Respect reduced-motion preferences
           ---------------------------------------------------------------- */
        @media (prefers-reduced-motion: reduce) {
          .hero-heading {
            transition: opacity 0.15s linear, transform 0.15s linear;
          }
          .hero-canvas {
            transition: opacity 0.15s linear;
          }
          .hero-scroll-line {
            animation: none;
          }
        }
      `}</style>
    </div>
  );
}