"use client";

import type { ComponentProps, ReactNode } from "react";

import Image from "next/image";
import Link from "next/link";
import { Fraunces, IBM_Plex_Mono } from "next/font/google";

import ServiceFaqAccordion from "@/components/Servicefaqaccordion";
import ServiceGallerySlider from "@/components/ServiceGallerySlider";
import ServiceSectionNav from "@/components/ServiceSectionNav";
import Reveal from "@/components/Reveal";
import TrustBar from "@/components/TrustBar";
import type { TrustBarItem } from "@/lib/services";

/* ==========================================================================
   FONTS
============================================================================ */

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-fraunces",
});

const plexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
  variable: "--font-plex-mono",
});

/* ==========================================================================
   TYPES
============================================================================ */

type ServiceType = "construction" | "trade" | "property";

export interface ServiceImage {
  url: string;
  alt: string;
}

export interface ServiceCta {
  label: string;
  href: string;
}

export interface ServiceSection {
  id: string;
  layout: "image-left" | "image-right";
  heading: string;

  /*
    HTML generated by RichTextEditor.
    Example: "<p>Content <strong>here</strong>.</p>"
  */
  body: string;

  image: ServiceImage;
  cta?: ServiceCta;
}

export interface ServiceProcessStep {
  step: number;
  title: string;

  /*
    HTML generated by RichTextEditor.
  */
  description: string;
}

export interface ServiceFaq {
  question: string;

  /*
    HTML generated by RichTextEditor.
  */
  answer: string;
}

export interface ServicePageData {
  slug: string;
  title: string;
  category: string;
  serviceType?: ServiceType;

  image: ServiceImage;

  /*
    HTML generated by RichTextEditor.
  */
  shortDescription: string;

  primaryCta?: ServiceCta;
  secondaryCta?: ServiceCta;

  sections: ServiceSection[];

  whatsIncluded?: {
    title?: string;

    /*
      HTML generated by RichTextEditor.
    */
    intro?: string;

    items: string[];
  };

  gallery?: ServiceImage[];

  processTitle?: string;

  /*
    HTML generated by RichTextEditor.
  */
  processDescription?: string;

  process?: ServiceProcessStep[];

  faqs?: ServiceFaq[];

  cta?: {
    title?: string;

    /*
      HTML generated by RichTextEditor.
    */
    content?: string;

    buttonLabel?: string;
    buttonHref?: string;
  };

  seo?: {
    metaTitle: string;
    metaDescription: string;
    keywords?: string[];
  };
}

/*
  Trust bar data can arrive from more than one source depending on where
  ServicePageContent is rendered from (the production page vs. a CMS/editor
  preview), and those sources don't always agree on field names or on
  whether an `id` is present at all. Rather than forcing every caller to
  conform to the strict TrustBarItem shape from lib/services.ts, accept
  this looser shape here and normalize it below before it reaches <TrustBar>.
*/
export type LooseTrustBarItem = {
  id?: string;
  label?: string;
  title?: string;
  value?: string;
  [key: string]: unknown;
};

interface ServicePageContentProps {
  service: ServicePageData;

  trustBarItems?: LooseTrustBarItem[];

  /*
    Production page passes the real quote form.
    The editor preview passes a visual-only quote form.
  */
  quoteForm: ReactNode;

  /*
    True when rendered inside the CMS/editor preview rather than the live
    production page. Not currently used to change this component's own
    markup, but accepted so callers like ServicePreview can pass it through
    without a type error. Reserved for future use (e.g. suppressing
    animations or `priority` image preloading inside an editor iframe).
  */
  preview?: boolean;
}

/* ==========================================================================
   HELPERS
============================================================================ */

function hasValue(value?: string | null): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

/*
  Never give Next Link an empty string. Empty links can cause navigation
  problems and do not have meaningful behavior in the editor preview.
*/
function safeHref(href?: string | null, fallback = "#quote") {
  return hasValue(href) ? href.trim() : fallback;
}

/*
  Normalizes whatever loose trust-bar data a caller passes in (CMS/editor
  config, hardcoded arrays, etc.) into the strict TrustBarItem[] shape
  <TrustBar> expects. Falls back through label -> title -> value for the
  display text, and generates a stable id from the index when one isn't
  provided. Items with no usable text are dropped.

  NOTE: <TrustBar>'s icon lookup is keyed by `id` (e.g. "insured", "team",
  "guarantee", "service", "recommended"). If the source data doesn't supply
  one of those ids, TrustBar falls back to its default icon for that item —
  that's a display detail to fix at the data source, not something this
  normalizer can guess correctly on its own.
*/
function normalizeTrustBarItems(
  items: LooseTrustBarItem[] | undefined,
): TrustBarItem[] {
  if (!items?.length) return [];

  return items
    .map((item, index) => {
      const label = item.label ?? item.title ?? item.value ?? "";

      return {
        id: hasValue(item.id) ? item.id!.trim() : `trust-${index}`,
        label,
      };
    })
    .filter((item): item is TrustBarItem => hasValue(item.label));
}

/*
  This renders the exact HTML emitted by RichTextEditor.

  IMPORTANT:
  Sanitize rich text in your API before persistence. Do not rely on this
  renderer as an HTML sanitizer.
*/
function RichText({
  html,
  fallback,
  className = "",
}: {
  html?: string | null;
  fallback?: string;
  className?: string;
}) {
  if (!hasValue(html)) {
    return fallback ? <p>{fallback}</p> : null;
  }

  return (
    <div
      className={className}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

function ImagePlaceholder({
  label,
  dark = false,
}: {
  label: string;
  dark?: boolean;
}) {
  return (
    <div
      className={`flex h-full w-full items-center justify-center px-5 text-center text-xs font-medium uppercase tracking-[0.16em] ${
        dark
          ? "bg-gradient-to-br from-[#1C1712] to-[#55453A] text-[#E8C599]/80"
          : "bg-gradient-to-br from-[#E8C599]/35 to-[#FAF7F2] text-[#8A8074]"
      }`}
    >
      {label}
    </div>
  );
}

function CornerTicks({
  tone = "brass",
  interactive = true,
}: {
  tone?: "brass" | "pale";
  interactive?: boolean;
}) {
  const stroke = tone === "pale" ? "#E8C599" : "#A26028";

  const corners = [
    { pos: "left-0 top-0", rotate: "" },
    { pos: "right-0 top-0", rotate: "rotate-90" },
    { pos: "right-0 bottom-0", rotate: "rotate-180" },
    { pos: "left-0 bottom-0", rotate: "-rotate-90" },
  ];

  return (
    <>
      {corners.map((corner) => (
        <svg
          key={corner.pos}
          aria-hidden="true"
          width="14"
          height="14"
          viewBox="0 0 14 14"
          fill="none"
          className={`pointer-events-none absolute ${corner.pos} ${corner.rotate} ${
            interactive
              ? "opacity-0 transition-opacity duration-300 ease-out group-hover:opacity-80 group-focus-within:opacity-80"
              : "opacity-60"
          }`}
        >
          <path
            d="M1 6.5V1H6.5"
            stroke={stroke}
            strokeWidth="1.3"
            strokeLinecap="round"
          />
        </svg>
      ))}
    </>
  );
}

function ArrowIcon({
  size = 13,
}: {
  size?: number;
}) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 14 14"
      fill="none"
      aria-hidden="true"
      className="transition-transform duration-200 ease-out group-hover:translate-x-[3px]"
    >
      <path
        d="M2 7H12M12 7L7.5 2.5M12 7L7.5 11.5"
        stroke="currentColor"
        strokeWidth="1.4"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function SectionDivider() {
  return (
    <div
      aria-hidden="true"
      className="relative h-px w-full bg-[#1C1712]/8"
    >
      <span className="absolute left-1/2 top-1/2 h-1.5 w-1.5 -translate-x-1/2 -translate-y-1/2 rotate-45 bg-[#E8C599]" />
    </div>
  );
}

/* ==========================================================================
   SHARED AREAS
============================================================================ */

const SHARED_AREAS = [
  "City of London",
  "Westminster",
  "Kensington & Chelsea",
  "Camden",
  "Islington",
  "Hackney",
  "Hammersmith & Fulham",
  "Wandsworth",
  "Richmond upon Thames",
  "Kingston upon Thames",
  "Merton",
  "Lambeth",
  "Southwark",
  "Lewisham",
  "Greenwich",
  "Tower Hamlets",
  "Haringey",
  "Barnet",
  "Brent",
  "Ealing",
  "Hounslow",
  "Enfield",
  "Bromley",
  "Croydon",
];

/* ==========================================================================
   COMPONENT
============================================================================ */

export default function ServicePageContent({
  service,
  trustBarItems,
  quoteForm,
  preview = false,
}: ServicePageContentProps) {
  // `preview` is reserved for future preview-only behaviour (e.g. disabling
  // the hero's `priority` image load or Ken Burns animation inside an
  // editor iframe). It intentionally isn't referenced yet.
  void preview;

  const galleryImages = (service.gallery ?? []).filter((image) =>
    hasValue(image.url),
  );

  const hasWhatsIncluded = (service.whatsIncluded?.items.length ?? 0) > 0;
  const hasFaqs = (service.faqs?.length ?? 0) > 0;
  const hasGallery = galleryImages.length > 0;
  const hasProcess = (service.process?.length ?? 0) > 0;

  const normalizedTrustBarItems = normalizeTrustBarItems(trustBarItems);

  const serviceType = service.serviceType ?? "trade";
  const isConstruction = serviceType === "construction";
  const isTrade = serviceType === "trade";

  const overviewTitle = isConstruction
    ? `A considered approach to ${service.title.toLowerCase()}.`
    : isTrade
      ? `Professional ${service.title.toLowerCase()}, carried out properly.`
      : `Reliable ${service.title.toLowerCase()} for your property.`;

  const overviewDescription = isConstruction
    ? "Every project is approached with the same focus on quality, clear communication and careful coordination. From the first conversation through to completion, our team keeps the work organised, transparent and accountable."
    : isTrade
      ? `Every ${service.title.toLowerCase()} job is approached with a focus on quality, clear communication and professional workmanship. From the initial enquiry through to completion, our team keeps the work organised, transparent and accountable.`
      : `Every ${service.title.toLowerCase()} service is approached with care, clear communication and attention to detail. Our team keeps the work organised, transparent and focused on delivering a properly finished result.`;

  const areasTitle = isConstruction
    ? "Delivering projects across London."
    : isTrade
      ? "Providing professional services across London."
      : "Supporting properties across London.";

  const areasDescription = isConstruction
    ? "BSL Construction works across London, supporting homeowners, developers, landlords, property managers and commercial clients with professional construction and property services."
    : isTrade
      ? `BSL Construction provides professional ${service.title.toLowerCase()} services across London for homeowners, landlords, property managers and commercial clients.`
      : "BSL Construction provides professional property services across London, supporting homeowners, landlords, property managers and commercial clients.";

  const quoteTitle = isConstruction
    ? `Let's talk about your ${service.title.toLowerCase()} project.`
    : isTrade
      ? `Let's talk about your ${service.title.toLowerCase()} needs.`
      : "Let's talk about your property requirements.";

  const quoteDescription = isConstruction
    ? "Tell us about your plans, your property and what you're looking to achieve. Our team will review your requirements and get back to you."
    : isTrade
      ? `Tell us what you need for your ${service.title.toLowerCase()}. Our team will review your requirements and get back to you with the next steps.`
      : "Tell us what you need and our team will review your requirements and get back to you with the next steps.";

  const closingTitle =
    service.cta?.title ||
    (isConstruction
      ? `Let's scope your ${service.title.toLowerCase()} project.`
      : isTrade
        ? `Need professional ${service.title.toLowerCase()}?`
        : "Let's discuss your property requirements.");

  const closingButton =
    service.cta?.buttonLabel ||
    (isConstruction ? "Discuss Your Project" : "Request a Quote");

  const inPageNav = [
    { href: "#overview", label: "Overview" },
    ...(hasWhatsIncluded
      ? [{ href: "#included", label: "What's included" }]
      : []),
    ...(hasGallery ? [{ href: "#gallery", label: "Gallery" }] : []),
    ...(hasProcess ? [{ href: "#process", label: "How it works" }] : []),
    { href: "#areas", label: "Areas we cover" },
    ...(hasFaqs ? [{ href: "#faqs", label: "FAQs" }] : []),
    { href: "#quote", label: "Get a quote" },
  ];

  return (
    <main className={`${fraunces.variable} ${plexMono.variable}`}>
      <style>{`
        .bsl-serif {
          font-family:
            var(--font-fraunces),
            "Iowan Old Style",
            "Palatino Linotype",
            Palatino,
            serif;
        }

        .bsl-mono {
          font-family:
            var(--font-plex-mono),
            ui-monospace,
            SFMono-Regular,
            "SF Mono",
            Menlo,
            Consolas,
            monospace;
        }

        .bsl-gold-rule {
          background: linear-gradient(
            90deg,
            transparent,
            #E8C599 45%,
            #E8C599 55%,
            transparent
          );
        }

        .bsl-focus:focus-visible {
          outline: 2px solid #A26028;
          outline-offset: 3px;
          border-radius: 4px;
        }

        .bsl-dot-grid {
          background-image:
            radial-gradient(
              circle,
              rgba(232, 197, 153, 0.16) 1px,
              transparent 1px
            );
          background-size: 22px 22px;
        }

        .bsl-grain {
          background-image:
            url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
          background-size: 160px 160px;
        }

        .bsl-rich-text > :first-child {
          margin-top: 0;
        }

        .bsl-rich-text > :last-child {
          margin-bottom: 0;
        }

        .bsl-rich-text p {
          margin: 0 0 1em;
        }

        .bsl-rich-text h3 {
          margin: 1.25em 0 0.5em;
          font-family: var(--font-fraunces), serif;
          font-size: 1.25em;
          font-weight: 600;
          line-height: 1.25;
          color: #1C1712;
        }

        .bsl-rich-text h4 {
          margin: 1.1em 0 0.5em;
          font-size: 1.05em;
          font-weight: 600;
          color: #1C1712;
        }

        .bsl-rich-text ul,
        .bsl-rich-text ol {
          margin: 0 0 1em;
          padding-left: 1.4em;
        }

        .bsl-rich-text ul {
          list-style: disc;
        }

        .bsl-rich-text ol {
          list-style: decimal;
        }

        .bsl-rich-text li + li {
          margin-top: 0.35em;
        }

        .bsl-rich-text a {
          color: #1F4B66;
          text-decoration: underline;
          text-underline-offset: 3px;
        }

        .bsl-rich-text blockquote {
          margin: 1em 0;
          border-left: 2px solid #A26028;
          padding-left: 1em;
          font-style: italic;
          color: #6E6259;
        }

        @keyframes bsl-kenburns {
          from {
            transform: scale(1.03) translate3d(0, 0, 0);
          }

          to {
            transform: scale(1.13) translate3d(-1.2%, -1%, 0);
          }
        }

        .bsl-hero-image {
          animation: bsl-kenburns 26s ease-in-out infinite alternate;
        }

        .bsl-section-image {
          transition:
            transform 0.9s cubic-bezier(0.16, 1, 0.3, 1),
            filter 0.9s ease;
        }

        .bsl-section-row:hover .bsl-section-image,
        .bsl-section-row:focus-within .bsl-section-image {
          transform: scale(1.06);
          filter: saturate(1.08) brightness(1.02);
        }

        @media (prefers-reduced-motion: reduce) {
          .bsl-hero-image {
            animation: none;
          }

          .bsl-section-image {
            transition: none;
          }

          .bsl-section-row:hover .bsl-section-image {
            transform: none;
            filter: none;
          }
        }
      `}</style>

      {/* HERO */}

      <header className="relative overflow-hidden px-5 pb-20 pt-32 sm:px-8 lg:px-12 lg:pb-28 lg:pt-40">
        <div className="absolute inset-0 overflow-hidden">
          {hasValue(service.image.url) ? (
            <Image
              src={service.image.url}
              alt={service.image.alt || service.title}
              fill
              priority
              sizes="100vw"
              className="bsl-hero-image object-cover"
            />
          ) : (
            <ImagePlaceholder label="Hero image" dark />
          )}
        </div>

        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 bg-gradient-to-b from-[#1C1712]/60 via-[#1C1712]/32 to-[#1C1712]/72"
        />

        <div
          aria-hidden="true"
          className="bsl-grain pointer-events-none absolute inset-0 opacity-[0.05] mix-blend-overlay"
        />

        <div
          aria-hidden="true"
          className="bsl-dot-grid pointer-events-none absolute inset-0 [mask-image:linear-gradient(to_bottom,black,transparent)]"
        />

        <div className="relative mx-auto max-w-[1180px]">
          <nav
            aria-label="Breadcrumb"
            className="bsl-mono mb-5 flex items-center gap-2 text-[0.72rem] uppercase tracking-[0.1em] text-white/55"
          >
            <Link href="/services" className="bsl-focus hover:text-white/90">
              Services
            </Link>

            <span aria-hidden="true">/</span>
            <span className="text-white/85">{service.title}</span>
          </nav>

          <span className="bsl-mono mb-4 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.28em] text-[#E8C599]">
            <span aria-hidden="true" className="h-px w-6 bg-[#E8C599]" />
            {service.category}
          </span>

          <h1 className="bsl-serif mb-5 max-w-2xl text-[clamp(2.6rem,5.6vw,4.2rem)] font-semibold leading-[1.05] tracking-[-0.02em] text-white">
            {service.title}
          </h1>

          <div aria-hidden="true" className="bsl-gold-rule mb-6 h-px w-24" />

          <RichText
            html={service.shortDescription}
            fallback="Service description will appear here."
            className="bsl-rich-text max-w-2xl text-[clamp(1.05rem,1.6vw,1.25rem)] leading-[1.75] text-white/70 [&_a]:text-[#E8C599]"
          />

          <div className="mt-9 flex flex-wrap items-center gap-4">
            <Link
              href={safeHref(service.primaryCta?.href)}
              className="bsl-focus group inline-flex items-center gap-2 rounded-full bg-[#A26028] px-7 py-3 text-[0.82rem] font-semibold uppercase tracking-[0.08em] text-white transition-all duration-200 ease-out hover:-translate-y-0.5 hover:bg-[#8A5121]"
            >
              {service.primaryCta?.label || "Get a Quote"}
              <ArrowIcon />
            </Link>

            {hasValue(service.secondaryCta?.label) && (
              <Link
                href={safeHref(service.secondaryCta?.href, "#overview")}
                className="bsl-focus bsl-mono text-[0.78rem] font-medium uppercase tracking-[0.06em] text-white/75 underline decoration-white/30 underline-offset-4 transition-colors hover:text-white"
              >
                {service.secondaryCta.label}
              </Link>
            )}
          </div>
        </div>
      </header>

      <TrustBar items={normalizedTrustBarItems} />

      <ServiceSectionNav items={inPageNav} />

      {/* OVERVIEW */}

      <section
        id="overview"
        className="scroll-mt-16 bg-[#FAF7F2] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"
      >
        <div className="mx-auto max-w-[1180px]">
          <div className="mb-16 grid gap-10 lg:mb-24 lg:grid-cols-[1fr_0.75fr] lg:items-end">
            <div>
              <span className="bsl-mono mb-4 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.24em] text-[#A26028]">
                <span aria-hidden="true" className="h-px w-6 bg-[#A26028]" />
                Overview
              </span>

              <h2 className="bsl-serif max-w-2xl text-[clamp(2rem,3.8vw,3.2rem)] font-semibold leading-[1.12] tracking-[-0.02em] text-[#1C1712]">
                {overviewTitle}
              </h2>
            </div>

            <div className="border-l border-[#A26028]/25 pl-6 lg:pl-8">
              <p className="text-[1rem] leading-[1.85] text-[#5C544A]">
                {overviewDescription}
              </p>

              <div className="mt-7 flex items-center gap-3">
                <span className="h-px w-8 bg-[#A26028]" />
                <span className="bsl-mono text-[0.68rem] font-medium uppercase tracking-[0.18em] text-[#A26028]">
                  BSL Construction
                </span>
              </div>
            </div>
          </div>

          <div className="space-y-28 lg:space-y-36">
            {service.sections.map((section, index) => {
              const imageOnRight = section.layout === "image-right";

              const position = `${String(index + 1).padStart(
                2,
                "0",
              )} / ${String(service.sections.length).padStart(2, "0")}`;

              return (
                <Reveal
                  key={section.id}
                  id={section.id}
                  className="scroll-mt-24"
                >
                  <div
                    className={`bsl-section-row group mx-auto flex max-w-[1080px] flex-col items-start gap-12 lg:gap-16 ${
                      imageOnRight ? "lg:flex-row-reverse" : "lg:flex-row"
                    }`}
                  >
                    <figure className="w-full shrink-0 lg:w-[46%]">
                      <div className="relative mx-auto max-w-[480px] p-4 lg:mx-0">
                        <span
                          aria-hidden="true"
                          className="absolute inset-2 -z-10 translate-x-3 translate-y-3 bg-[#E8C599]/25 lg:translate-x-4 lg:translate-y-4"
                        />

                        <div className="relative bg-[#FAF7F2] p-2.5 shadow-[0_1px_3px_rgba(28,23,18,0.08)] ring-1 ring-[#1C1712]/[0.06]">
                          <CornerTicks />

                          <div className="relative aspect-[6/7] w-full overflow-hidden">
                            {hasValue(section.image.url) ? (
                              <Image
                                src={section.image.url}
                                alt={section.image.alt || section.heading}
                                fill
                                sizes="(min-width: 1024px) 480px, 86vw"
                                className="bsl-section-image object-cover"
                              />
                            ) : (
                              <ImagePlaceholder
                                label={`Image for ${
                                  section.heading || "section"
                                }`}
                              />
                            )}
                          </div>
                        </div>
                      </div>

                      <figcaption className="mt-3 flex items-baseline gap-3 px-4">
                        <span className="bsl-mono shrink-0 text-[0.68rem] font-medium tracking-[0.08em] text-[#A26028]">
                          Fig. {String(index + 1).padStart(2, "0")}
                        </span>

                        <span className="bsl-mono text-[0.72rem] leading-snug tracking-[0.01em] text-[#8A8074]">
                          {section.image.alt ||
                            section.heading ||
                            "Image to be added"}
                        </span>
                      </figcaption>
                    </figure>

                    <div className="w-full lg:w-[50%] lg:pt-8">
                      <span className="bsl-mono mb-4 inline-flex items-center gap-3 text-[0.68rem] font-medium tracking-[0.2em] text-[#A26028]">
                        <span
                          aria-hidden="true"
                          className="h-px w-6 bg-[#A26028]/60"
                        />
                        {position}
                      </span>

                      <h3 className="bsl-serif mb-5 max-w-[26ch] text-[clamp(1.7rem,2.8vw,2.35rem)] font-medium leading-[1.22] tracking-[-0.01em] text-[#1C1712]">
                        {section.heading || "Section title"}
                      </h3>

                      <RichText
                        html={section.body}
                        fallback="Section content will appear here."
                        className="bsl-rich-text mb-7 max-w-[50ch] text-[1rem] leading-[1.9] text-[#5C544A]"
                      />

                      {hasValue(section.cta?.label) && (
                        <Link
                          href={safeHref(section.cta?.href)}
                          className="bsl-focus group/cta inline-flex items-center gap-2 rounded-full border border-[#A26028] px-5 py-2.5 text-[0.76rem] font-semibold uppercase tracking-[0.06em] text-[#A26028] transition-all duration-200 ease-out hover:bg-[#A26028] hover:text-white"
                        >
                          {section.cta.label}
                          <ArrowIcon size={12} />
                        </Link>
                      )}
                    </div>
                  </div>
                </Reveal>
              );
            })}
          </div>
        </div>
      </section>

      <SectionDivider />

      {/* WHAT'S INCLUDED */}

      {hasWhatsIncluded && (
        <>
          <section
            id="included"
            className="scroll-mt-16 bg-white px-5 py-20 sm:px-8 lg:px-10 lg:py-28"
          >
            <div className="mx-auto max-w-[1180px]">
              <div className="grid gap-10 border-b border-[#1C1712]/10 pb-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-end">
                <div>
                  <span className="bsl-mono mb-4 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.24em] text-[#A26028]">
                    <span aria-hidden="true" className="h-px w-6 bg-[#A26028]" />
                    {service.whatsIncluded?.title || "What's Included"}
                  </span>

                  <h2 className="bsl-serif max-w-xl text-[clamp(2rem,3.5vw,2.8rem)] font-semibold leading-[1.12] tracking-[-0.02em] text-[#1C1712]">
                    A complete service, carefully coordinated.
                  </h2>
                </div>

                <RichText
                  html={service.whatsIncluded?.intro}
                  fallback="From the initial scope through to completion, our team coordinates the essential elements of the work with a clear focus on quality, safety and a properly finished result."
                  className="bsl-rich-text text-[1rem] leading-[1.85] text-[#5C544A] lg:max-w-xl lg:justify-self-end"
                />
              </div>

              <div className="mt-12 grid gap-x-10 gap-y-0 md:grid-cols-2 lg:grid-cols-3">
                {service.whatsIncluded?.items.map((item, index) => (
                  <Reveal
                    key={`${item}-${index}`}
                    delay={Math.min(index * 60, 240)}
                    className="group relative border-b border-[#1C1712]/10 py-7 first:pt-0 md:nth-[2]:pt-0 lg:nth-[3]:pt-0"
                  >
                    <div className="flex items-start gap-5">
                      <span className="bsl-mono shrink-0 text-[0.7rem] font-medium tracking-[0.12em] text-[#A26028]">
                        {String(index + 1).padStart(2, "0")}
                      </span>

                      <div>
                        <div className="mb-3 flex h-8 w-8 items-center justify-center rounded-full bg-[#1C1712] text-[#E8C599] transition-colors duration-300 group-hover:bg-[#A26028]">
                          ✓
                        </div>

                        <p className="max-w-[28ch] text-[0.98rem] font-medium leading-[1.65] text-[#1C1712]">
                          {item}
                        </p>
                      </div>
                    </div>
                  </Reveal>
                ))}
              </div>

              <div className="mt-12 flex flex-col gap-5 border-t border-[#1C1712]/10 pt-8 sm:flex-row sm:items-center sm:justify-between">
                <p className="bsl-mono max-w-xl text-[0.72rem] uppercase leading-[1.7] tracking-[0.08em] text-[#8A8074]">
                  Scope and specification are confirmed before work begins,
                  so you have a clear understanding of what is included.
                </p>

                <Link
                  href="#quote"
                  className="bsl-focus group inline-flex shrink-0 items-center gap-2 text-[0.78rem] font-semibold uppercase tracking-[0.08em] text-[#A26028]"
                >
                  Discuss Your Requirements
                  <ArrowIcon />
                </Link>
              </div>
            </div>
          </section>

          <SectionDivider />
        </>
      )}

      {/* GALLERY */}

      {hasGallery && (
        <>
          <section
            id="gallery"
            className="scroll-mt-16 bg-[#FAF7F2] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"
          >
            <div className="mx-auto max-w-[1080px]">
              <div className="mb-9 flex flex-wrap items-end justify-between gap-4">
                <div>
                  <span className="bsl-mono mb-3 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.24em] text-[#A26028]">
                    <span aria-hidden="true" className="h-px w-6 bg-[#A26028]" />
                    Gallery
                  </span>

                  <h2 className="bsl-serif max-w-2xl text-[clamp(1.7rem,2.8vw,2.2rem)] font-semibold leading-[1.15] text-[#1C1712]">
                    A closer look at {service.title.toLowerCase()} on site.
                  </h2>
                </div>

                <p className="bsl-mono text-[0.78rem] tracking-[0.01em] text-[#6E6259]">
                  Tap a photo to view it full-screen, or use the arrows to
                  browse.
                </p>
              </div>

              <ServiceGallerySlider
                images={galleryImages}
                title={service.title}
              />
            </div>
          </section>

          <SectionDivider />
        </>
      )}

      {/* PROCESS */}

      {hasProcess && (
        <>
          <section
            id="process"
            className="scroll-mt-16 bg-white px-5 py-20 sm:px-8 lg:py-28"
          >
            <div className="mx-auto max-w-[780px]">
              <span className="bsl-mono mb-3 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.24em] text-[#A26028]">
                <span aria-hidden="true" className="h-px w-6 bg-[#A26028]" />
                How it works
              </span>

              <h2 className="bsl-serif mb-4 text-[clamp(1.7rem,2.8vw,2.2rem)] font-semibold leading-[1.15] text-[#1C1712]">
                {service.processTitle || "From first visit to completion"}
              </h2>

              <RichText
                html={service.processDescription}
                className="bsl-rich-text mb-11 max-w-xl text-[1rem] leading-[1.7] text-[#5C544A]"
              />

              <ol className="relative space-y-11 border-l border-[#1C1712]/10 pl-9">
                {service.process?.map((step, index) => (
                  <Reveal
                    as="li"
                    key={step.step}
                    delay={Math.min(index * 80, 240)}
                    className="relative"
                  >
                    <span
                      aria-hidden="true"
                      className="bsl-mono absolute -left-[2.95rem] flex h-10 w-10 items-center justify-center rounded-full border border-[#A26028]/25 bg-[#1C1712] text-[0.82rem] font-medium text-[#E8C599]"
                    >
                      {String(step.step).padStart(2, "0")}
                    </span>

                    <p className="bsl-mono mb-1.5 text-[0.68rem] font-medium uppercase tracking-[0.22em] text-[#A26028]">
                      Step {String(step.step).padStart(2, "0")}
                    </p>

                    <h3 className="bsl-serif mb-2 text-[1.2rem] font-semibold text-[#1C1712]">
                      {step.title || `Step ${step.step}`}
                    </h3>

                    <RichText
                      html={step.description}
                      fallback="Step content will appear here."
                      className="bsl-rich-text max-w-lg text-[1rem] leading-[1.75] text-[#5C544A]"
                    />
                  </Reveal>
                ))}
              </ol>
            </div>
          </section>

          <SectionDivider />
        </>
      )}

      {/* AREAS */}

      <section
        id="areas"
        className="scroll-mt-16 bg-[#1C1712] px-5 py-20 text-white sm:px-8 lg:px-10 lg:py-28"
      >
        <div className="mx-auto max-w-[1180px]">
          <div className="grid gap-14 lg:grid-cols-[0.8fr_1.2fr]">
            <div>
              <span className="bsl-mono mb-4 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.24em] text-[#E8C599]">
                <span aria-hidden="true" className="h-px w-6 bg-[#E8C599]" />
                Areas We Cover
              </span>

              <h2 className="bsl-serif max-w-md text-[clamp(2rem,3.5vw,2.8rem)] font-semibold leading-[1.12] tracking-[-0.02em]">
                {areasTitle}
              </h2>

              <p className="mt-6 max-w-md text-[1rem] leading-[1.85] text-white/60">
                {areasDescription}
              </p>

              <Link
                href="#quote"
                className="bsl-focus group mt-8 inline-flex items-center gap-2 rounded-full border border-[#E8C599]/50 px-5 py-2.5 text-[0.76rem] font-semibold uppercase tracking-[0.06em] text-[#E8C599] transition-colors hover:bg-[#E8C599] hover:text-[#1C1712]"
              >
                {isConstruction ? "Discuss Your Project" : "Request a Quote"}
                <ArrowIcon size={12} />
              </Link>
            </div>

            <div className="grid grid-cols-2 gap-x-6 gap-y-0 border-t border-white/10 sm:grid-cols-3">
              {SHARED_AREAS.map((area, index) => (
                <div
                  key={area}
                  className="flex items-center gap-3 border-b border-white/10 py-5"
                >
                  <span className="bsl-mono text-[0.62rem] text-[#E8C599]/60">
                    {String(index + 1).padStart(2, "0")}
                  </span>

                  <span className="text-[0.88rem] text-white/75">{area}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <SectionDivider />

      {/* FAQS */}

      {hasFaqs && (
        <section
          id="faqs"
          className="scroll-mt-16 bg-[#FAF7F2] px-5 py-20 sm:px-8 lg:py-28"
        >
          <div className="mx-auto max-w-[820px]">
            <span className="bsl-mono mb-3 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.24em] text-[#A26028]">
              <span aria-hidden="true" className="h-px w-6 bg-[#A26028]" />
              Questions
            </span>

            <h2 className="bsl-serif mb-9 text-[clamp(1.7rem,2.8vw,2.2rem)] font-semibold leading-[1.15] text-[#1C1712]">
              Frequently asked about {service.title.toLowerCase()}
            </h2>

            {/*
              ServiceFaqAccordion must render FAQ answers as HTML too.
              See the note below this file.
            */}
            <ServiceFaqAccordion faqs={service.faqs ?? []} />
          </div>
        </section>
      )}

      {/* QUOTE */}

      <section
        id="quote"
        className="scroll-mt-16 bg-[#FAF7F2] px-5 py-20 sm:px-8 lg:px-10 lg:py-28"
      >
        <div className="mx-auto max-w-[1180px]">
          <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20">
            <div>
              <span className="bsl-mono mb-4 inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.24em] text-[#A26028]">
                <span aria-hidden="true" className="h-px w-6 bg-[#A26028]" />
                Get a Quote
              </span>

              <h2 className="bsl-serif max-w-lg text-[clamp(2rem,3.8vw,3.2rem)] font-semibold leading-[1.12] tracking-[-0.02em] text-[#1C1712]">
                {quoteTitle}
              </h2>

              <p className="mt-6 max-w-lg text-[1rem] leading-[1.85] text-[#5C544A]">
                {quoteDescription}
              </p>

              <div className="mt-8 border-l border-[#A26028]/30 pl-6">
                <p className="bsl-mono text-[0.7rem] uppercase tracking-[0.12em] text-[#8A8074]">
                  Service enquiry
                </p>

                <p className="mt-2 text-sm font-medium text-[#1C1712]">
                  {service.title}
                </p>
              </div>
            </div>

            <div>{quoteForm}</div>
          </div>
        </div>
      </section>

      {/* CLOSING CTA */}

      <div className="bg-white px-5 py-14 sm:px-8 lg:px-10 lg:py-16">
        <Reveal className="relative mx-auto flex max-w-[1180px] flex-col items-start gap-6 overflow-hidden rounded-[28px] bg-[#1C1712] px-7 py-10 sm:px-10 lg:flex-row lg:items-center lg:justify-between lg:px-14 lg:py-14">
          <div
            aria-hidden="true"
            className="bsl-grain pointer-events-none absolute inset-0 opacity-[0.05] mix-blend-overlay"
          />

          <div className="relative max-w-lg">
            <span className="bsl-mono mb-3 inline-flex items-center gap-2 text-[0.66rem] font-medium uppercase tracking-[0.24em] text-[#E8C599]">
              Ready to start?
            </span>

            <h2 className="bsl-serif mb-3 text-[clamp(1.6rem,2.9vw,2.2rem)] font-semibold leading-tight text-white">
              {closingTitle}
            </h2>

            <RichText
              html={service.cta?.content}
              fallback="Tell us what you need and we’ll come back with a clear, honest scope — no obligation, no upsell."
              className="bsl-rich-text text-[1rem] leading-[1.65] text-white/65 [&_a]:text-[#E8C599] [&_h3]:text-white [&_h4]:text-white"
            />
          </div>

          <Link
            href={safeHref(service.cta?.buttonHref)}
            className="bsl-focus group relative inline-flex shrink-0 items-center gap-2 rounded-full bg-[#A26028] px-7 py-3.5 text-[0.88rem] font-semibold uppercase tracking-[0.08em] text-white transition-all duration-200 ease-out hover:-translate-y-0.5 hover:bg-[#8A5121]"
          >
            {closingButton}
            <ArrowIcon size={14} />
          </Link>
        </Reveal>
      </div>
    </main>
  );
}